/* =============================================================================
   THE HANDLEY CUP — PLAYER DATA
   Generated from Handley_Cup_Master_Sheet.xlsx (Player Profile Data Set tab).

   RULES:
   - If a Best Run / timeline result doesn't specify which competition,
     default to "Handley Cup".
   - Averages were only tracked from the 24/25 season onward.
   - Best Run = best Handley Cup result if the player ever reached the
     Handley Cup bracket; otherwise their best Parson's Plate result.
   - Scores marked with "(reconstructed)" were recovered from a spreadsheet
     auto-date-conversion bug — double check these against DartConnect
     where possible.

   opponentId links to another profile automatically if that opponent
   exists in this file. If null, the name displays as plain text.
   ========================================================================= */

// Flip this to true once the Interesting Facts / Stats data has been
// tidied up and you're happy for it to go live. Until then, every profile
// shows a "being finalised" placeholder instead — the fact data underneath
// is untouched and ready to go the moment you flip this.
const FACTS_READY = true;

const PLAYERS = [
  {
    id: "hedley-paul-keegan",
    name: "Hedley-Paul Keegan",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Last 16" },
    nickname: "The Sauce",
    writeup: `The fresher, the pretender, the sauce! Underwhelmed last year after mopping up Players Champs. Backing the lad to bounce back in spades and claim more than a few titles next season`,
    highestAverage: { value: 66.58, link: "https://recap.dartconnect.com/matches/6974e94e0efa95bbe4954944" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "25/26", competition: "Handley Cup", result: "Last 16", opponentId: "will-north", opponentName: "Will North", score: "0-4", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "oliver-wilson",
    name: "Oliver Wilson",
    appearances: 3,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Runner-Up" },
    nickname: "Wicked",
    writeup: `Wicked Wicked Wilson is massive. Everyone's favourite shithouse brummy. It just wouldn't be the Handley cup without him. Losing to Hugo in the final was heartbreak for Wils. Bounced back last year to get out of his group and showed multiple 60+ averages`,
    highestAverage: { value: 61.42, link: "https://recap.dartconnect.com/matches/69750f830efa95bbe4958121" },
    oneEighties: 2,
    quickestLeg: null,
    highestCheckout: { value: 119, link: null },
    facts: [],
    placeholder: false,
    timeline: [
      { year: "23/24", competition: "Handley Cup", result: "Last 16", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "0-4", scoreReconstructed: false, average: null, link: null },
      { year: "24/25", competition: "Parson's Plate", result: "Runner-Up", opponentId: "hugo-nilsson", opponentName: "Hugo Nilsson", score: "2-4", scoreReconstructed: true, average: null, link: null },
      { year: "25/26", competition: "Handley Cup", result: "Last 24", opponentId: "will-ellis", opponentName: "Will Ellis", score: "1-4", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "alex-wright",
    name: "Alex Wright",
    appearances: 7,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Semi-Final" },
    nickname: "One to Watch",
    writeup: `The One To Watch, every single year! 7 years on the trot has the Wright stuff turned up smiling and lobbing! A corner stone of the society and a friendly face. Alex is Hallam darts - win or lose we're on the booze!`,
    highestAverage: { value: 47.7, link: "https://recap.dartconnect.com/matches/6974f3040efa95bbe4955611" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "19/20", competition: "Parson's Plate", result: "Semi-Final", opponentId: "laura-bugge", opponentName: "Laura Bugge", score: "1-2", scoreReconstructed: true, average: null, link: null },
      { year: "20/21", competition: "Parson's Plate", result: "Quarter-Final", opponentId: "nathan-hemmingway", opponentName: "Nathan Hemmingway", score: "0-3", scoreReconstructed: false, average: null, link: null },
      { year: "21/22", competition: "Parson's Plate", result: "Runner-Up", opponentId: "cam-thorpe", opponentName: "Cam Thorpe", score: "0-3", scoreReconstructed: false, average: null, link: null },
      { year: "22/23", competition: "Handley Cup", result: "Last 16", opponentId: "zach-hodgson", opponentName: "Zach Hodgson", score: "0-4", scoreReconstructed: false, average: null, link: null },
      { year: "23/24", competition: "Parson's Plate", result: "Semi-Final", opponentId: "finley-sanderson", opponentName: "Finley Sanderson", score: "0-4", scoreReconstructed: false, average: null, link: null },
      { year: "24/25", competition: "Parson's Plate", result: "Last 16", opponentId: "hugo-nilsson", opponentName: "Hugo Nilsson", score: "1-3", scoreReconstructed: true, average: null, link: null },
      { year: "25/26", competition: "Parson's Plate", result: "Last 24", opponentId: "todd-haynes", opponentName: "Todd Haynes", score: "0-3", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "jessie-sale",
    name: "Jessie Sale",
    appearances: 4,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Quarter-Final" },
    nickname: "Half Price",
    writeup: `The TikTok sensation and Paddy Power Princess, Jessie loves the darts. The most capped female in Handley Cup history and Hallam Darts history, Jessie is making her 4th appearance including last year, no shoes and hair brush in hand. Jessie is a Handley cup staple, when she isn't showing her face on mainstream TV!`,
    highestAverage: { value: 58.1, link: "https://recap.dartconnect.com/matches/6974d4080efa95bbe4952e83" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "21/22", competition: "Handley Cup", result: "Quarter-Final", opponentId: "jamie-flint", opponentName: "Jamie Flint", score: "0-3", scoreReconstructed: false, average: null, link: null },
      { year: "22/23", competition: "Handley Cup", result: "Last 16", opponentId: "oli-bartlett", opponentName: "Oli Bartlett", score: "0-4", scoreReconstructed: false, average: null, link: null },
      { year: "23/24", competition: "Parson's Plate", result: "Quarter-Final", opponentId: "alex-wright", opponentName: "Alex Wright", score: "0-3", scoreReconstructed: false, average: null, link: null },
      { year: "25/26", competition: "Parson's Plate", result: "Last 24", opponentId: "thomas-palmer", opponentName: "Thomas Palmer", score: "1-3", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "dan-harrison",
    name: "Dan Harrison",
    appearances: 5,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Semi-Final" },
    nickname: "Mr Mardy",
    writeup: `Someone needs to carry Dale and Rushy's darts I guess! The Return of Mr Mardy has been class to see, putting in some good averages over the last 2 seasons of the Handley cup and somebody that will have his eyes set firmly on the Parsons plate - but he may hope for an easier group this year`,
    highestAverage: { value: 60.62, link: "https://recap.dartconnect.com/matches/6974f2980efa95bbe4955570" },
    oneEighties: 3,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "18/19", competition: "Handley Cup", result: "Quarter-Final", opponentId: "dale-dennett", opponentName: "Dale Dennett", score: "1-4", scoreReconstructed: false, average: null, link: null },
      { year: "19/20", competition: "Parson's Plate", result: "Semi-Final", opponentId: "nathan-hemmingway", opponentName: "Nathan Hemmingway", score: "1-2", scoreReconstructed: true, average: null, link: null },
      { year: "20/21", competition: "Parson's Plate", result: "Quarter-Final", opponentId: "jamesey-ennis", opponentName: "Jamesey Ennis", score: "2-3", scoreReconstructed: true, average: null, link: null },
      { year: "24/25", competition: "Parson's Plate", result: "Semi-Final", opponentId: "oliver-wilson", opponentName: "Oliver Wilson", score: "1-3", scoreReconstructed: true, average: null, link: null },
      { year: "25/26", competition: "Parson's Plate", result: "Semi-Final", opponentId: "reuben-evans", opponentName: "Reuben Evans", score: "2-4", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "todd-haynes",
    name: "Todd Haynes",
    appearances: 8,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Winner" },
    nickname: "Super Todd",
    writeup: `Super Todd! 8 year mainstay, 1 of only 4 players to never miss an event. Todd's results have been a real mixed bag from Semi finals to early plate exits, but no one can take the Parsons Plate away from the Super. A true hero of the society, beware his drunk texts and rambles in a group chat and his fishing frenzy habits....`,
    highestAverage: { value: 58.56, link: "https://recap.dartconnect.com/matches/6974eea30efa95bbe4955048" },
    oneEighties: 1,
    quickestLeg: null,
    highestCheckout: { value: 120, link: null },
    facts: [],
    placeholder: false,
    timeline: [
      { year: "18/19", competition: "Handley Cup", result: "Quarter-Final", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "0-4", scoreReconstructed: false, average: null, link: null },
      { year: "19/20", competition: "Handley Cup", result: "Quarter-Final", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "1-3", scoreReconstructed: true, average: null, link: null },
      { year: "20/21", competition: "Handley Cup", result: "Semi-Final", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "1-5", scoreReconstructed: true, average: null, link: null },
      { year: "21/22", competition: "Handley Cup", result: "Quarter-Final", opponentId: "deck-ingber", opponentName: "Deck Ingber", score: "1-3", scoreReconstructed: true, average: null, link: null },
      { year: "22/23", competition: "Parson's Plate", result: "Semi-Final", opponentId: "oli-gubbins", opponentName: "Oli Gubbins", score: "1-4", scoreReconstructed: true, average: null, link: null },
      { year: "23/24", competition: "Parson's Plate", result: "Winner", opponentId: "finley-sanderson", opponentName: "Finley Sanderson", score: "5-2", scoreReconstructed: true, average: null, link: null },
      { year: "24/25", competition: "Parson's Plate", result: "Semi-Final", opponentId: "hugo-nilsson", opponentName: "Hugo Nilsson", score: "1-3", scoreReconstructed: true, average: null, link: null },
      { year: "25/26", competition: "Parson's Plate", result: "Last 16", opponentId: "reuben-evans", opponentName: "Reuben Evans", score: "0-3", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "eddie-castaldo",
    name: "Eddie Castaldo",
    appearances: 5,
    nationality: "Italy",
    bestRun: { label: "Parson's Plate", detail: "Winner" },
    nickname: "The Eagle",
    writeup: `The Eagle! 5 appearances to his name and always box office for his rivalry vs Thorpe! Last year the eagle let his darts do the talking with a massive Parson's plate win, with a first 9 of over 70 in the event he cleaned up to pick up his first title at the event, normally getting to later stages of the Cup but a brutal group was a blessing in disguise as the Eagle landed some silverware!`,
    highestAverage: { value: 80.52, link: "https://recap.dartconnect.com/matches/6974dc870efa95bbe4953955" },
    oneEighties: 3,
    quickestLeg: { darts: 14, link: null },
    highestCheckout: { value: 115, link: null },
    facts: [],
    placeholder: false,
    timeline: [
      { year: "20/21", competition: "Handley Cup", result: "Semi-Final", opponentId: "dale-dennett", opponentName: "Dale Dennett", score: "0-5", scoreReconstructed: false, average: null, link: null },
      { year: "22/23", competition: "Handley Cup", result: "Last 16", opponentId: "jamie-flint", opponentName: "Jamie Flint", score: "2-4", scoreReconstructed: true, average: null, link: null },
      { year: "23/24", competition: "Handley Cup", result: "Quarter-Final", opponentId: "bradley-truelove", opponentName: "Bradley Truelove", score: "1-4", scoreReconstructed: true, average: null, link: null },
      { year: "24/25", competition: "Handley Cup", result: "Last 16", opponentId: "curtis-thorpe", opponentName: "Curtis Thorpe", score: "1-4", scoreReconstructed: true, average: null, link: null },
      { year: "25/26", competition: "Parson's Plate", result: "Winner", opponentId: "reuben-evans", opponentName: "Reuben Evans", score: "1-5", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "blake-longden",
    name: "Blake Longden",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Quarter-Final" },
    nickname: "The SuperStyler",
    writeup: `Slongden was buzzing to get the invite and get back playing, since the event Blake has gone from strength to strength and credits Thorpe and the Handley cup for all success and now Thorpe can't get near him. Blake is already eyeing up the Handley Cup next season`,
    highestAverage: { value: 53.05, link: "https://recap.dartconnect.com/matches/697519ce0efa95bbe4959178" },
    oneEighties: 2,
    quickestLeg: null,
    highestCheckout: { value: 111, link: null },
    facts: [],
    placeholder: false,
    timeline: [
      { year: "25/26", competition: "Parson's Plate", result: "Quarter-Final", opponentId: "reuben-evans", opponentName: "Reuben Evans", score: "3-4", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "charlie-marshall",
    name: "Charlie Marshall",
    appearances: 8,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Winner" },
    nickname: "The Fire",
    writeup: `The G.O.A.T - The BackToBackToBackToBackToBackToBackToBack Champ - Holding the 180, quick leg and high checkout record. One of the ever-presents at the event. A semi finalist first time out, but COVID wasn't even a thing the last time Charlie Marshall lost a game at the Handley Cup. Making his way into the professional game with Challenge Tours and Exhibition work. Truly the best`,
    highestAverage: { value: 92.02, link: "https://recap.dartconnect.com/matches/6782743c167d4efa93f7be73" },
    oneEighties: 35,
    quickestLeg: { darts: 12, link: null },
    highestCheckout: { value: 148, link: null },
    facts: [],
    placeholder: false,
    timeline: [
      { year: "18/19", competition: "Handley Cup", result: "Semi-Final", opponentId: "will-sturla", opponentName: "Will Sturla", score: "1-5", scoreReconstructed: false, average: null, link: null },
      { year: "19/20", competition: "Handley Cup", result: "Winner", opponentId: "jamie-flint", opponentName: "Jamie Flint", score: "5-4", scoreReconstructed: true, average: null, link: null },
      { year: "20/21", competition: "Handley Cup", result: "Winner", opponentId: "dale-dennett", opponentName: "Dale Dennett", score: "6-0", scoreReconstructed: false, average: null, link: null },
      { year: "21/22", competition: "Handley Cup", result: "Winner", opponentId: "bart-timmer", opponentName: "Bart Timmer", score: "5-3", scoreReconstructed: true, average: null, link: null },
      { year: "22/23", competition: "Handley Cup", result: "Winner", opponentId: "connor-bowler", opponentName: "Connor Bowler", score: "6-4", scoreReconstructed: true, average: null, link: null },
      { year: "23/24", competition: "Handley Cup", result: "Winner", opponentId: "oliver-burgess", opponentName: "Oliver Burgess", score: "6-2", scoreReconstructed: true, average: null, link: null },
      { year: "24/25", competition: "Handley Cup", result: "Winner", opponentId: "morgan-shillito", opponentName: "Morgan Shillito", score: "6-0", scoreReconstructed: false, average: null, link: null },
      { year: "25/26", competition: "Handley Cup", result: "Winner", opponentId: "oliver-burgess", opponentName: "Oliver Burgess", score: "7-4", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "morgan-shillito",
    name: "Morgan Shillito",
    appearances: 4,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Runner-Up" },
    nickname: "Captain",
    writeup: `He hit a 9 darter once, did he tell you!? Mog is part of the trio responsible for Hallam's golden generation, won just about everything in the UDUK and even hit the winning dart at Varsity....I think? Morgan has enjoyed a great run to the final in 24/25 where he was whacked by Marshall. The Donny boy is always slapping in some 180s when he attends, a great watch and even better ball knowledge.`,
    highestAverage: { value: 82.7, link: "https://recap.dartconnect.com/matches/6974e2f20efa95bbe4954170" },
    oneEighties: 20,
    quickestLeg: null,
    highestCheckout: { value: 100, link: null },
    facts: [],
    placeholder: false,
    timeline: [
      { year: "22/23", competition: "Handley Cup", result: "Last 16", opponentId: "connor-bowler", opponentName: "Connor Bowler", score: "1-4", scoreReconstructed: true, average: null, link: null },
      { year: "23/24", competition: "Handley Cup", result: "Quarter-Final", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "1-4", scoreReconstructed: true, average: null, link: null },
      { year: "24/25", competition: "Handley Cup", result: "Runner-Up", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "0-6", scoreReconstructed: false, average: null, link: null },
      { year: "25/26", competition: "Handley Cup", result: "Quarter-Final", opponentId: "oliver-burgess", opponentName: "Oliver Burgess", score: "1-5", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "will-ellis",
    name: "Will Ellis",
    appearances: 3,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Last 16" },
    nickname: "Lisandro",
    writeup: `It's honestly a mystery how this man has not made it to the quarter finals! Some rotten draws vs Bowler, Marshall and OPB! (Go for the plate son, you'll piss it!) Lisandaro is a Hallam Darts legend and league winning captain and some 70 averages in the Handley Cup shows his quality - coming to an Ambulance near you, with his hand eye coordination you'll be just fine!`,
    highestAverage: { value: 70.38, link: "https://recap.dartconnect.com/matches/678288a0167d4efa93f7ce8c" },
    oneEighties: 4,
    quickestLeg: null,
    highestCheckout: { value: 110, link: null },
    facts: [],
    placeholder: false,
    timeline: [
      { year: "23/24", competition: "Handley Cup", result: "Last 16", opponentId: "connor-bowler", opponentName: "Connor Bowler", score: "1-4", scoreReconstructed: true, average: null, link: null },
      { year: "24/25", competition: "Handley Cup", result: "Last 16", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "2-4", scoreReconstructed: true, average: null, link: null },
      { year: "25/26", competition: "Handley Cup", result: "Last 16", opponentId: "oliver-burgess", opponentName: "Oliver Burgess", score: "0-4", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "louis-bell",
    name: "Louis Bell",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Semi-Final" },
    nickname: "Hells",
    writeup: `The new kid on the block. Louis turned up to the Handley cup last season with high hopes and left with a hangover and a case of what could have been getting slaughtered at the bar and in the semi final, next year Hells?`,
    highestAverage: { value: 72.73, link: "https://recap.dartconnect.com/matches/6974f3040efa95bbe4955611" },
    oneEighties: 3,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "25/26", competition: "Handley Cup", result: "Semi-Final", opponentId: "oliver-burgess", opponentName: "Oliver Burgess", score: "1-6", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "josh-longden",
    name: "Josh Longden",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Last 16" },
    nickname: "The Juggernaut",
    writeup: `Missed match darts against Morgan and a historic miscount! He was the overachiever of last year's event, here's hoping he hits the practice board and carries it on this year`,
    highestAverage: { value: 65.35, link: "https://recap.dartconnect.com/matches/6974ff8d0efa95bbe4956764" },
    oneEighties: 1,
    quickestLeg: null,
    highestCheckout: { value: 104, link: null },
    facts: [],
    placeholder: false,
    timeline: [
      { year: "25/26", competition: "Handley Cup", result: "Last 16", opponentId: "morgan-shillito", opponentName: "Morgan Shillito", score: "3-4", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "jack-whiteley",
    name: "Jack Whiteley",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Last 24" },
    nickname: "Frost",
    writeup: `Frost has been so tidy at the PCs this year, he was an outside chance to make a deep run or win the plate. Sadly he ran into Moggy in his arena of Yorkshire Main, averages clocking over 60 for Jack shows he has a touch of class and ability`,
    highestAverage: { value: 61.37, link: "https://recap.dartconnect.com/matches/69750db00efa95bbe4957e3c" },
    oneEighties: 1,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "25/26", competition: "Handley Cup", result: "Last 24", opponentId: "morgan-shillito", opponentName: "Morgan Shillito", score: "1-4", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "finley-nottingham",
    name: "Finley Nottingham",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Last 16" },
    nickname: "Chippy",
    writeup: `A unit of a man faced the group of death last year. Hoping for some easier reps on the board next season. He faced the highest average in last year's group stage`,
    highestAverage: { value: 42.42, link: "https://recap.dartconnect.com/matches/6974d9fd0efa95bbe4953609" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "25/26", competition: "Parson's Plate", result: "Last 16", opponentId: "matt-davies", opponentName: "Matt Davies", score: "0-3", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "dale-dennett",
    name: "Dale Dennett",
    appearances: 7,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Runner-Up" },
    nickname: "Double D",
    writeup: `The Man The Myth The Spreadsheet! Double D is always a welcome sight at the Handley cup leading the chants or asking about every stat under the sun or talking about the glory days of board 5 at Hubs. Dennett has an incredible legacy at the Handley Cup! 2x runner-up and a few semis to his name, a real threat to any player and knock-off football shirt provider please use code: DENNETT at DHGATE today for 20% off!`,
    highestAverage: { value: 72.84, link: "https://recap.dartconnect.com/matches/6782c6b0167d4efa93f811c0" },
    oneEighties: 3,
    quickestLeg: null,
    highestCheckout: { value: 146, link: null },
    facts: [],
    placeholder: false,
    timeline: [
      { year: "18/19", competition: "Handley Cup", result: "Runner-Up", opponentId: "will-sturla", opponentName: "Will Sturla", score: "1-6", scoreReconstructed: false, average: null, link: null },
      { year: "19/20", competition: "Handley Cup", result: "Quarter-Final", opponentId: "jamie-flint", opponentName: "Jamie Flint", score: "1-3", scoreReconstructed: true, average: null, link: null },
      { year: "20/21", competition: "Handley Cup", result: "Runner-Up", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "0-6", scoreReconstructed: false, average: null, link: null },
      { year: "22/23", competition: "Handley Cup", result: "Semi-Final", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "0-5", scoreReconstructed: false, average: null, link: null },
      { year: "23/24", competition: "Handley Cup", result: "Quarter-Final", opponentId: "jamie-flint", opponentName: "Jamie Flint", score: "2-4", scoreReconstructed: true, average: null, link: null },
      { year: "24/25", competition: "Handley Cup", result: "Semi-Final", opponentId: "morgan-shillito", opponentName: "Morgan Shillito", score: "2-5", scoreReconstructed: true, average: null, link: null },
      { year: "25/26", competition: "Handley Cup", result: "Last 16", opponentId: "louis-bell", opponentName: "Louis Bell", score: "3-4", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "will-north",
    name: "Will North",
    appearances: 2,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Quarter-Final" },
    nickname: "King of the North",
    writeup: `Umi of Derby and he has somehow snuck his way into the Handley Cup!? Northy is class and after a year away came back firing last year with a quarter final lost to debutant Louis Bell. Once he learns what his pint limit is I think North could be a sneaky shout for an even better run at the Handley Cup`,
    highestAverage: { value: 73.76, link: "https://recap.dartconnect.com/matches/6974cbdb0efa95bbe495238f" },
    oneEighties: 1,
    quickestLeg: { darts: 14, link: null },
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "23/24", competition: "Handley Cup", result: "Last 16", opponentId: "jamie-flint", opponentName: "Jamie Flint", score: "0-4", scoreReconstructed: false, average: null, link: null },
      { year: "25/26", competition: "Handley Cup", result: "Quarter-Final", opponentId: "louis-bell", opponentName: "Louis Bell", score: "2-5", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "catlin-cope",
    name: "Catlin Cope",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Last 24" },
    nickname: "Can't Cope",
    writeup: `I can't cope with the fact you lost to Kel and it took an hour, and even worse Dan put you at the bottom of the power rankings, but you did prove him wrong! Catlin and Kel are busy practising together I'm sure`,
    highestAverage: { value: 43.18, link: "https://recap.dartconnect.com/matches/6974dada0efa95bbe4953743" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "25/26", competition: "Parson's Plate", result: "Last 24", opponentId: "kelham-elliot", opponentName: "Kelham Elliot", score: "2-3", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "hugo-nilsson",
    name: "Hugo Nilsson",
    appearances: 3,
    nationality: "Sweden",
    bestRun: { label: "Parson's Plate", detail: "Winner" },
    nickname: "The Scandinavian Express",
    writeup: `The Swede boasts 3 appearances at the Handley Cup, a member of the Hallam golden age. A historic Parson's plate win over Wicked Wilson in 24/25 cemented his legacy as a Hallam all timer, played his way into form last year resulting in the first time he made it out the groups in the Cup, trending in the right direction`,
    highestAverage: { value: 57.62, link: "https://recap.dartconnect.com/matches/6974fcfc0efa95bbe4956391" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: { value: 118, link: null },
    facts: [],
    placeholder: false,
    timeline: [
      { year: "23/24", competition: "Parson's Plate", result: "Quarter-Final", opponentId: "todd-haynes", opponentName: "Todd Haynes", score: "0-3", scoreReconstructed: false, average: null, link: null },
      { year: "24/25", competition: "Parson's Plate", result: "Winner", opponentId: "oliver-wilson", opponentName: "Oliver Wilson", score: "4-2", scoreReconstructed: true, average: null, link: null },
      { year: "25/26", competition: "Handley Cup", result: "Last 24", opponentId: "hedley-paul-keegan", opponentName: "Hedley-Paul Keegan", score: "1-4", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "tom-russell",
    name: "Tom Russell",
    appearances: 2,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Last 16" },
    nickname: "Winger",
    writeup: `The Mullet and tache combo is the strongest thing about Russell on the oche but the boy loves a pint and always keen for a hot take. Russell will be backing up Burton next time out and we cannot wait`,
    highestAverage: { value: 45.08, link: "https://recap.dartconnect.com/matches/67826e69167d4efa93f7ba4d" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "24/25", competition: "Parson's Plate", result: "Last 16", opponentId: "jack-clucas", opponentName: "Jack Clucas", score: "1-3", scoreReconstructed: true, average: null, link: null },
      { year: "25/26", competition: "Parson's Plate", result: "Last 24", opponentId: "joe-ellett", opponentName: "Joe Ellett", score: "0-3", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "tom-hodder",
    name: "Tom Hodder",
    appearances: 2,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Last 16" },
    nickname: "Hound Dog",
    writeup: `Hounddog and a 124 on the bull, name a better combo...that's right the AA! Hodder has improved so much since the first Handley cup but yet to make it count, a run next year for the Hounddog in the plate is a real tasty outside bet`,
    highestAverage: { value: 46.32, link: "https://recap.dartconnect.com/matches/6974f0520efa95bbe4955279" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: { value: 124, link: null },
    facts: [],
    placeholder: false,
    timeline: [
      { year: "24/25", competition: "Parson's Plate", result: "Last 32", opponentId: "alex-botha", opponentName: "Alex Botha", score: "1-3", scoreReconstructed: true, average: null, link: null },
      { year: "25/26", competition: "Parson's Plate", result: "Last 16", opponentId: "joe-ellett", opponentName: "Joe Ellett", score: "1-3", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "ben-pellington",
    name: "Ben Pellington",
    appearances: 2,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Last 24" },
    nickname: "The Potter",
    writeup: `The Potter is one of the new era at Hallam Darts, 2 appearances to his name and some steady averages to his name! Progressing into the Cup last season before falling to the ever classy James Buckby`,
    highestAverage: { value: 54.67, link: "https://recap.dartconnect.com/matches/6974c3f50efa95bbe4951a14" },
    oneEighties: 1,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "24/25", competition: "Parson's Plate", result: "Last 32", opponentId: "dan-harrison", opponentName: "Dan Harrison", score: "1-3", scoreReconstructed: true, average: null, link: null },
      { year: "25/26", competition: "Handley Cup", result: "Last 24", opponentId: "james-buckby", opponentName: "James Buckby", score: "0-4", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "luke-mccormack",
    name: "Luke McCormack",
    appearances: 2,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Quarter-Final" },
    nickname: "Mr See It Off",
    writeup: `The best dressed man Hallam Darts has ever seen and not too bad at downing pints too....Gemma Collins' favourite player and all around stattoo, the less said about Luke throwing the darts the better.`,
    highestAverage: { value: 52.88, link: "https://recap.dartconnect.com/matches/6974c4a10efa95bbe4951ae0" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "24/25", competition: "Parson's Plate", result: "Quarter-Final", opponentId: "todd-haynes", opponentName: "Todd Haynes", score: "0-3", scoreReconstructed: false, average: null, link: null },
      { year: "25/26", competition: "Parson's Plate", result: "Last 24", opponentId: "finley-nottingham", opponentName: "Finley Nottingham", score: "0-3", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "dereece-ohara",
    name: "Dereece O'Hara",
    appearances: 3,
    nationality: "Jamaica",
    bestRun: { label: "Parson's Plate", detail: "Quarter-Final" },
    nickname: "The Jamaican Sensation",
    writeup: `If we don't talk about his Varsity performances and more about him having his airpods surgically removed from his ears. The Jamaican Sensation is always a tricky customer in the Handley cup snatching group stage games if you're not on your A game, having some rough draws vs Thorpe, Tofts and Castaldo to end his campaigns earlier than he would have liked`,
    highestAverage: { value: 58.56, link: "https://recap.dartconnect.com/matches/67826ef5167d4efa93f7bab1" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "22/23", competition: "Handley Cup", result: "Last 16", opponentId: "curtis-thorpe", opponentName: "Curtis Thorpe", score: "1-4", scoreReconstructed: true, average: null, link: null },
      { year: "24/25", competition: "Handley Cup", result: "Last 16", opponentId: "dom-tofts", opponentName: "Dom Tofts", score: "1-4", scoreReconstructed: true, average: null, link: null },
      { year: "25/26", competition: "Parson's Plate", result: "Quarter-Final", opponentId: "eddie-castaldo", opponentName: "Eddie Castaldo", score: "0-4", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "callum-woodcock",
    name: "Callum Woodcock",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Quarter-Final" },
    nickname: "Timberdick",
    writeup: `Your Pres next year. Timberdick played in a pretty stacked group with legends such as Ingber and Flint and acquitted himself very well, the second highest running average of the Plate on debut but ran into Eddie to end his hopes. Callum will look to improve next season and make a claim on the Cup or at least ruin a few people's runs...`,
    highestAverage: { value: 69.6, link: "https://recap.dartconnect.com/matches/6974f0600efa95bbe495528e" },
    oneEighties: 1,
    quickestLeg: null,
    highestCheckout: { value: 112, link: null },
    facts: [],
    placeholder: false,
    timeline: [
      { year: "25/26", competition: "Parson's Plate", result: "Quarter-Final", opponentId: "eddie-castaldo", opponentName: "Eddie Castaldo", score: "1-4", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "thomas-palmer",
    name: "Thomas Palmer",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Last 16" },
    nickname: "Palmer",
    writeup: `Palmer made a good account of himself on debut and was unlucky with the draw in the plate to run into an unstoppable Castaldo`,
    highestAverage: { value: 57.91, link: "https://recap.dartconnect.com/matches/69751dda0efa95bbe49597c9" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "25/26", competition: "Parson's Plate", result: "Last 16", opponentId: "eddie-castaldo", opponentName: "Eddie Castaldo", score: "0-3", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "reuben-evans",
    name: "Reuben Evans",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Runner-Up" },
    nickname: "Flobnut",
    writeup: `A final on your debut isn't bad going! Evans ran into Castaldo but a 15 darter on the way isn't too bad! Reuben will be looking to go 1 better next season I'm sure, good darts from a promising talent`,
    highestAverage: { value: 56.81, link: "https://recap.dartconnect.com/matches/69752ba60efa95bbe495aeb6" },
    oneEighties: 1,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "25/26", competition: "Parson's Plate", result: "Runner-Up", opponentId: "eddie-castaldo", opponentName: "Eddie Castaldo", score: "1-5", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "jamie-flint",
    name: "Jamie Flint",
    appearances: 8,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Runner-Up" },
    nickname: "Flinty",
    writeup: `The biggest head of the Mount Rushmore, one of only 4 players to play in every edition. Started out as a promising young fresher and quickly became a mainstay in the back end of early editions of the Handley Cup. Missing match darts against the 7 time Champ Charlie twice, Flinty has swapped the arrows for the golf clubs, still attending and showing his face even if the averages are starting to fall. A Hallam Legend.`,
    highestAverage: { value: 59.61, link: "https://recap.dartconnect.com/matches/6782a773167d4efa93f7ecdf" },
    oneEighties: 7,
    quickestLeg: { darts: 15, link: null },
    highestCheckout: { value: 118, link: null },
    facts: ["Only Player to Miss Match Darts vs Charlie Marshall in Years he has lifted the title (23/24)"],
    placeholder: false,
    timeline: [
      { year: "18/19", competition: "Handley Cup", result: "Last 16", opponentId: "oli-bartlett", opponentName: "Oli Bartlett", score: "2-3", scoreReconstructed: false, average: null, link: null },
      { year: "19/20", competition: "Handley Cup", result: "Runner-Up", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "4-5", scoreReconstructed: true, average: null, link: null },
      { year: "20/21", competition: "Handley Cup", result: "Quarter-Final", opponentId: "todd-haynes", opponentName: "Todd Haynes", score: "2-4", scoreReconstructed: true, average: null, link: null },
      { year: "21/22", competition: "Handley Cup", result: "Semi-Final", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "0-4", scoreReconstructed: false, average: null, link: null },
      { year: "22/23", competition: "Handley Cup", result: "Quarter-Final", opponentId: "dale-dennett", opponentName: "Dale Dennett", score: "2-4", scoreReconstructed: true, average: null, link: null },
      { year: "23/24", competition: "Handley Cup", result: "Semi-Final", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "4-5", scoreReconstructed: true, average: null, link: null },
      { year: "24/25", competition: "Handley Cup", result: "Last 16", opponentId: "morgan-shillito", opponentName: "Morgan Shillito", score: "1-4", scoreReconstructed: true, average: null, link: null },
      { year: "25/26", competition: "Handley Cup", result: "Last 24", opponentId: "dom-tofts", opponentName: "Dom Tofts", score: "3-4", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "dan-rushton",
    name: "Dan Rushton",
    appearances: 3,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Quarter-Final" },
    nickname: "Rushy",
    writeup: `Rushy's hiatus did him the world of good, not since Covid did he see the Scouser until he rocked up at the 24/25 edition and was throwing 70 averages like he was born to do it! But the duo of Dennett and Tofts sending Rushy to the bar like the Hallam of old. A very dangerous player who is far better than his runs suggest, never bet against Dan to make a deep run!`,
    highestAverage: { value: 78.87, link: "https://recap.dartconnect.com/matches/678294e1167d4efa93f7d91e" },
    oneEighties: 8,
    quickestLeg: { darts: 13, link: null },
    highestCheckout: { value: 130, link: null },
    facts: ["Longest Wait between Appearences (4 events)"],
    placeholder: false,
    timeline: [
      { year: "20/21", competition: "Parson's Plate", result: "Quarter-Final", opponentId: "oli-gubbins", opponentName: "Oli Gubbins", score: "2-3", scoreReconstructed: true, average: null, link: null },
      { year: "24/25", competition: "Handley Cup", result: "Last 16", opponentId: "dale-dennett", opponentName: "Dale Dennett", score: "1-4", scoreReconstructed: true, average: null, link: null },
      { year: "25/26", competition: "Handley Cup", result: "Quarter-Final", opponentId: "dom-tofts", opponentName: "Dom Tofts", score: "3-5", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "jono-downing",
    name: "Jono Downing",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Last 16" },
    nickname: "The Havoc",
    writeup: `Chaos, shithouse, box office. Jono made it out of the groups and went on a tidy little run. More of the same this season as he looks to be an A team staple`,
    highestAverage: { value: 57.08, link: "https://recap.dartconnect.com/matches/6974dbf80efa95bbe49538ae" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: { value: 100, link: null },
    facts: [],
    placeholder: false,
    timeline: [
      { year: "25/26", competition: "Handley Cup", result: "Last 16", opponentId: "dom-tofts", opponentName: "Dom Tofts", score: "3-4", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "kelham-elliot",
    name: "Kelham Elliot",
    appearances: 3,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Quarter-Final" },
    nickname: "The Telescope Maker",
    writeup: `The Miller loves the Handley cup that much he played 1 game that took a shade under an hour! The Telescope Maker is part of the golden age of Hallam backing up the B team with some impressive wins. 3 plate outings for Kel but little to show for it in the KO games`,
    highestAverage: { value: 50.05, link: "https://recap.dartconnect.com/matches/6974d84c0efa95bbe49533ea" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: { value: 116, link: null },
    facts: [],
    placeholder: false,
    timeline: [
      { year: "23/24", competition: "Parson's Plate", result: "Quarter-Final", opponentId: "nathan-stewart", opponentName: "Nathan Stewart", score: "1-3", scoreReconstructed: true, average: null, link: null },
      { year: "24/25", competition: "Parson's Plate", result: "Last 16", opponentId: "luke-mccormack", opponentName: "Luke McCormack", score: "1-3", scoreReconstructed: true, average: null, link: null },
      { year: "25/26", competition: "Parson's Plate", result: "Last 16", opponentId: "dereece-ohara", opponentName: "Dereece O'Hara", score: "0-3", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "matt-davies",
    name: "Matt Davies",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Quarter-Final" },
    nickname: "Miracle Maker",
    writeup: `Dumbbells and doubles for Davies. The boy can play and press. Matt is always an outside shot to cause an upset or have a run in the plate`,
    highestAverage: { value: 55.85, link: "https://recap.dartconnect.com/matches/6974c4980efa95bbe4951ad0" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "25/26", competition: "Parson's Plate", result: "Quarter-Final", opponentId: "dereece-ohara", opponentName: "Dereece O'Hara", score: "2-4", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "curtis-thorpe",
    name: "Curtis Thorpe",
    appearances: 8,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Semi-Final" },
    nickname: "Thorpedo",
    writeup: `The man who created The Handley Cup, Mr Hallam Darts some would call him. He loves the Handley Cup so much every year he picks a different player to beat him! The best 1 handed dart player in Hallam History and will teach you not to square your flights and how dart weight does not matter. But ultimately he just wants Hallam Darts to grow as well as the Handley Cup (he's only cried a few times)`,
    highestAverage: { value: 69.58, link: "https://recap.dartconnect.com/matches/6974ebbb0efa95bbe4954c6e" },
    oneEighties: 2,
    quickestLeg: { darts: 15, link: null },
    highestCheckout: { value: 122, link: null },
    facts: [],
    placeholder: false,
    timeline: [
      { year: "18/19", competition: "Handley Cup", result: "Last 16", opponentId: "dale-dennett", opponentName: "Dale Dennett", score: "1-3", scoreReconstructed: false, average: null, link: null },
      { year: "19/20", competition: "Handley Cup", result: "Semi-Final", opponentId: "jamie-flint", opponentName: "Jamie Flint", score: "2-4", scoreReconstructed: true, average: null, link: null },
      { year: "20/21", competition: "Handley Cup", result: "Quarter-Final", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "2-4", scoreReconstructed: true, average: null, link: null },
      { year: "21/22", competition: "Handley Cup", result: "Quarter-Final", opponentId: "bart-timmer", opponentName: "Bart Timmer", score: "1-3", scoreReconstructed: false, average: null, link: null },
      { year: "22/23", competition: "Handley Cup", result: "Quarter-Final", opponentId: "connor-bowler", opponentName: "Connor Bowler", score: "1-4", scoreReconstructed: true, average: null, link: null },
      { year: "23/24", competition: "Handley Cup", result: "Last 16", opponentId: "eddie-castaldo", opponentName: "Eddie Castaldo", score: "3-4", scoreReconstructed: true, average: null, link: null },
      { year: "24/25", competition: "Handley Cup", result: "Quarter-Final", opponentId: "morgan-shillito", opponentName: "Morgan Shillito", score: "3-4", scoreReconstructed: true, average: null, link: null },
      { year: "25/26", competition: "Handley Cup", result: "Last 16", opponentId: "dan-rushton", opponentName: "Dan Rushton", score: "3-4", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "joe-ellett",
    name: "Joe Ellett",
    appearances: 3,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Quarter-Final" },
    nickname: "Blonde Joevi",
    writeup: `Blonde Joevi is known best for his part in the Varsity winning side and always letting people know if he's hit a 26 or a 140....Truelove broke his heart in back to back years before a plate run was snuffed out last season vs Harrison. His group-stage match vs Rushton in 24/25 lives long in the memory`,
    highestAverage: { value: 66.31, link: "https://recap.dartconnect.com/matches/678290f8167d4efa93f7d56b" },
    oneEighties: 3,
    quickestLeg: null,
    highestCheckout: { value: 100, link: null },
    facts: [],
    placeholder: false,
    timeline: [
      { year: "23/24", competition: "Handley Cup", result: "Last 16", opponentId: "bradley-truelove", opponentName: "Bradley Truelove", score: "0-4", scoreReconstructed: false, average: null, link: null },
      { year: "24/25", competition: "Handley Cup", result: "Last 16", opponentId: "bradley-truelove", opponentName: "Bradley Truelove", score: "1-4", scoreReconstructed: true, average: null, link: null },
      { year: "25/26", competition: "Parson's Plate", result: "Quarter-Final", opponentId: "dan-harrison", opponentName: "Dan Harrison", score: "2-4", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "olly-doherty",
    name: "Olly Doherty",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Last 16" },
    nickname: "Gunnie Winnie",
    writeup: `A quick improver with natural talent and the aura to match Olly is one to look out for in the upcoming season. A team regular? It's on the cards...`,
    highestAverage: { value: 57.59, link: "https://recap.dartconnect.com/matches/6974deac0efa95bbe4953c09" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "25/26", competition: "Parson's Plate", result: "Last 16", opponentId: "dan-harrison", opponentName: "Dan Harrison", score: "2-3", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "will-burgess",
    name: "Will Burgess",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Last 24" },
    nickname: "BBL City",
    writeup: `BBL city is a staple of Hallam and not just for his Batty helping the Bs and Cs. Attending the Handley cup lobbing arrows and sinking pints, should see his face in plenty more events`,
    highestAverage: { value: 43.33, link: "https://recap.dartconnect.com/matches/6974d4500efa95bbe4952ed9" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "25/26", competition: "Parson's Plate", result: "Last 24", opponentId: "dan-harrison", opponentName: "Dan Harrison", score: "0-3", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "jack-clucas",
    name: "Jack Clucas",
    appearances: 3,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Quarter-Final" },
    nickname: "Jack, Sack and Crack",
    writeup: `The man with an opinion on everything and the wind-up merchant himself. Jack Sack and Crack is loved by Hallam Darts for his league winning D6 to his Varsity Presenting. Clucas is a staple but the runs don't make for good reading, I can see this hunk make a Parsons plate final soon enough.`,
    highestAverage: { value: 55.87, link: "https://recap.dartconnect.com/matches/6974ebc70efa95bbe4954c81" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "23/24", competition: "Handley Cup", result: "Last 16", opponentId: "oliver-burgess", opponentName: "Oliver Burgess", score: "0-4", scoreReconstructed: false, average: null, link: null },
      { year: "24/25", competition: "Parson's Plate", result: "Quarter-Final", opponentId: "hugo-nilsson", opponentName: "Hugo Nilsson", score: "2-3", scoreReconstructed: true, average: null, link: null },
      { year: "25/26", competition: "Handley Cup", result: "Last 24", opponentId: "dale-dennett", opponentName: "Dale Dennett", score: "2-4", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "finley-sanderson",
    name: "Finley Sanderson",
    appearances: 3,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Runner-Up" },
    nickname: "Sharky",
    writeup: `Sharky has made 3 appearances on the spin, from being bested in the Final by Haynes on debut to getting out of the groups last year, Sharky loves the Handley cup, despite leaving uni he's never left Hallam Darts behind. His 3 eliminations have all come at the hands of players who attended the first ever Handley Cup`,
    highestAverage: { value: 55.41, link: "https://recap.dartconnect.com/matches/69750bc20efa95bbe4957b41" },
    oneEighties: 1,
    quickestLeg: null,
    highestCheckout: { value: 112, link: null },
    facts: [],
    placeholder: false,
    timeline: [
      { year: "23/24", competition: "Parson's Plate", result: "Runner-Up", opponentId: "todd-haynes", opponentName: "Todd Haynes", score: "2-5", scoreReconstructed: true, average: null, link: null },
      { year: "24/25", competition: "Parson's Plate", result: "Last 16", opponentId: "dan-harrison", opponentName: "Dan Harrison", score: "2-3", scoreReconstructed: true, average: null, link: null },
      { year: "25/26", competition: "Handley Cup", result: "Last 24", opponentId: "curtis-thorpe", opponentName: "Curtis Thorpe", score: "0-4", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "dom-tofts",
    name: "Dom Tofts",
    appearances: 4,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Semi-Final" },
    nickname: "Loftus Toftus",
    writeup: `Thank god the Handley Cup has an oche! Dommo's legacy spans across so many eras in Hallam Darts, he even attended The Handley Cup on his birthday and led Hallam to the first title outside of uni darts for the Scholars. Never practices and is more focused on his rollups but can still throw a class dart - 2 semi finals and 2 quarters is a sneakily impressive record for Dom`,
    highestAverage: { value: 66.12, link: "https://recap.dartconnect.com/matches/69752bd40efa95bbe495af05" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "19/20", competition: "Handley Cup", result: "Semi-Final", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "1-4", scoreReconstructed: true, average: null, link: null },
      { year: "20/21", competition: "Handley Cup", result: "Quarter-Final", opponentId: "eddie-castaldo", opponentName: "Eddie Castaldo", score: "2-4", scoreReconstructed: true, average: null, link: null },
      { year: "24/25", competition: "Handley Cup", result: "Quarter-Final", opponentId: "oliver-burgess", opponentName: "Oliver Burgess", score: "0-4", scoreReconstructed: false, average: null, link: null },
      { year: "25/26", competition: "Handley Cup", result: "Semi-Final", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "1-6", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "james-buckby",
    name: "James Buckby",
    appearances: 3,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Quarter-Final" },
    nickname: "Shuffle",
    writeup: `Part of the Hallam Golden age, won everything in the UDUK. Modus finalist. World Youth champ qualifier but he just can't seem to do it when it really matters (The Handley Cup, obvs!) his match vs Marshall last year was cruel, after a group of death and Marshall in the last 8 not even a near 89 average could save Shuffle. A future champion of the Handley Cup? I say so! (He's in your head....)`,
    highestAverage: { value: 88.26, link: "https://recap.dartconnect.com/matches/697514880efa95bbe495896b" },
    oneEighties: 7,
    quickestLeg: { darts: 13, link: null },
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "22/23", competition: "Handley Cup", result: "Last 16", opponentId: "dale-dennett", opponentName: "Dale Dennett", score: "2-4", scoreReconstructed: true, average: null, link: null },
      { year: "24/25", competition: "Handley Cup", result: "Quarter-Final", opponentId: "dale-dennett", opponentName: "Dale Dennett", score: "3-4", scoreReconstructed: true, average: null, link: null },
      { year: "25/26", competition: "Handley Cup", result: "Last 16", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "1-4", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "oliver-burgess",
    name: "Oliver Burgess",
    appearances: 4,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Runner-Up" },
    nickname: "The Notorious OPB",
    writeup: `The Notorious Cheeky Monkey. The practice board weeps when he enters a room. A key part of Hallam's golden era and one hell of a man! 4 years at the Handley cup and always getting at least to the last 4 - the only players to beat Burgess at the Handley Cup are the duo of Tenpin and the Fire. Dev Tour Finalist, 9 dart king and UDUK major winner will get his hands on this title one day I'm sure of it!`,
    highestAverage: { value: 87.92, link: "https://recap.dartconnect.com/matches/678294e1167d4efa93f7d91e" },
    oneEighties: 12,
    quickestLeg: { darts: 13, link: null },
    highestCheckout: { value: 110, link: null },
    facts: [],
    placeholder: false,
    timeline: [
      { year: "22/23", competition: "Handley Cup", result: "Semi-Final", opponentId: "connor-bowler", opponentName: "Connor Bowler", score: "1-5", scoreReconstructed: true, average: null, link: null },
      { year: "23/24", competition: "Handley Cup", result: "Runner-Up", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "2-6", scoreReconstructed: true, average: null, link: null },
      { year: "24/25", competition: "Handley Cup", result: "Semi-Final", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "3-5", scoreReconstructed: true, average: null, link: null },
      { year: "25/26", competition: "Handley Cup", result: "Runner-Up", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "4-7", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "bradley-truelove",
    name: "Bradley Truelove",
    appearances: 3,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Semi-Final" },
    nickname: "TheOne",
    writeup: `The One! Slay King! The Scholar and Capturing Hallam Hearts all the way from Halifax Banking. 3 appearances for Brad with a SF and 2 QFs to his name, always a danger to any player and did go within 1 leg of beating the Fire last season, he has only been stopped by OPB or Marshall. Brad is one to look out for, with his scoring power he could beat anyone, shame about the Instagram stories...`,
    highestAverage: { value: 76.01, link: "https://recap.dartconnect.com/matches/6975227a0efa95bbe4959fff" },
    oneEighties: 4,
    quickestLeg: { darts: 13, link: null },
    highestCheckout: { value: 106, link: null },
    facts: [],
    placeholder: false,
    timeline: [
      { year: "23/24", competition: "Handley Cup", result: "Semi-Final", opponentId: "oliver-burgess", opponentName: "Oliver Burgess", score: "3-5", scoreReconstructed: true, average: null, link: null },
      { year: "24/25", competition: "Handley Cup", result: "Quarter-Final", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "0-4", scoreReconstructed: false, average: null, link: null },
      { year: "25/26", competition: "Handley Cup", result: "Quarter-Final", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "4-5", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "alex-howes",
    name: "Alex Howes",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Last 16" },
    nickname: "ShitHowes",
    writeup: `Shithowes was the last man to sign up to the event but not the first out, unlucky in a tight group for Alex, being beaten by his future captain Woodcock`,
    highestAverage: { value: 58.74, link: "https://recap.dartconnect.com/matches/6974f3890efa95bbe49556c5" },
    oneEighties: 1,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "25/26", competition: "Parson's Plate", result: "Last 16", opponentId: "callum-woodcock", opponentName: "Callum Woodcock", score: "0-3", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "billy-bennett",
    name: "Billy Bennett",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Last 16" },
    nickname: "Triple B",
    writeup: `Dale Dennett's Regen strikes, the strides this man has taken in just 12 months is class from Cs to the A team and beating Ingber 4-3 in the process to place in the last 16 on debut is class from Triple B and will put him in good stead to lead Hallam this year!`,
    highestAverage: { value: 57.77, link: "https://recap.dartconnect.com/matches/6974e77f0efa95bbe4954716" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "25/26", competition: "Handley Cup", result: "Last 16", opponentId: "bradley-truelove", opponentName: "Bradley Truelove", score: "0-4", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "dan-burton",
    name: "Dan Burton",
    appearances: 2,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Last 16" },
    nickname: "Flamingo",
    writeup: `The Pep of Hallam Darts, Burton normally lets his boys do the talking, being a league winning president. The Flamingo loves Hallam just as much as Thorpe it's rumoured....Making 2 appearances at the Handley Cup and more to be added for sure, he also showed why he is ranked above Kel in the groups last year, the group chat went silent from the telescope maker`,
    highestAverage: { value: 49.0, link: "https://recap.dartconnect.com/matches/6974ef3f0efa95bbe4955102" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "24/25", competition: "Parson's Plate", result: "Last 16", opponentId: "zach-hodgson", opponentName: "Zach Hodgson", score: "1-3", scoreReconstructed: true, average: null, link: null },
      { year: "25/26", competition: "Parson's Plate", result: "Last 16", opponentId: "blake-longden", opponentName: "Blake Longden", score: "0-3", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "deck-ingber",
    name: "Deck Ingber",
    appearances: 7,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Semi-Final" },
    nickname: "Double Deckker",
    writeup: `He normally does alright when Thorpe isn't rigging the draw to watch the mild-mannered Ingber explode. A Hallam dart legend and a reason The Handley cup is what it is, always downing pints and missing doubles Donny's number 1 is destined to win the plate on the 10 year anniversary!`,
    highestAverage: { value: 60.4, link: "https://recap.dartconnect.com/matches/6974f0600efa95bbe495528e" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: { value: 125, link: null },
    facts: [],
    placeholder: false,
    timeline: [
      { year: "18/19", competition: "Handley Cup", result: "Quarter-Final", opponentId: "kieran-fitzgibbon", opponentName: "Kieran Fitzgibbon", score: "1-4", scoreReconstructed: false, average: null, link: null },
      { year: "19/20", competition: "Handley Cup", result: "Last 16", opponentId: "joe-evans", opponentName: "Joe Evans", score: "2-3", scoreReconstructed: true, average: null, link: null },
      { year: "20/21", competition: "Handley Cup", result: "Last 16", opponentId: "oli-bartlett", opponentName: "Oli Bartlett", score: "1-4", scoreReconstructed: true, average: null, link: null },
      { year: "21/22", competition: "Handley Cup", result: "Semi-Final", opponentId: "bart-timmer", opponentName: "Bart Timmer", score: "0-4", scoreReconstructed: false, average: null, link: null },
      { year: "22/23", competition: "Handley Cup", result: "Last 16", opponentId: "oliver-burgess", opponentName: "Oliver Burgess", score: "3-4", scoreReconstructed: true, average: null, link: null },
      { year: "24/25", competition: "Parson's Plate", result: "Last 32", opponentId: "hugo-nilsson", opponentName: "Hugo Nilsson", score: "2-3", scoreReconstructed: true, average: null, link: null },
      { year: "25/26", competition: "Handley Cup", result: "Last 24", opponentId: "billy-bennett", opponentName: "Billy Bennett", score: "3-4", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "chris-ward",
    name: "Chris Ward",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Last 24" },
    nickname: "The Warden",
    writeup: `Chris is quickly becoming a pivotal part of Hallam darts and we're backing him to be a regular at the Handley cup's future`,
    highestAverage: { value: 48.64, link: "https://recap.dartconnect.com/matches/6974ff8d0efa95bbe4956764" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "25/26", competition: "Parson's Plate", result: "Last 24", opponentId: "alex-howes", opponentName: "Alex Howes", score: "0-3", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "alex-botha",
    name: "Alex Botha",
    appearances: 1,
    nationality: "South Africa",
    bestRun: { label: "Parson's Plate", detail: "Last 16" },
    nickname: "Box Office",
    writeup: `Alex attended the event in 2024/25`,
    highestAverage: { value: 43.7, link: "https://recap.dartconnect.com/matches/67829f92167d4efa93f7e3ba" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "24/25", competition: "Parson's Plate", result: "Last 16", opponentId: "todd-haynes", opponentName: "Todd Haynes", score: "1-3", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "joe-evans",
    name: "Joe Evans",
    appearances: 3,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Quarter-Final" },
    nickname: "Mongo",
    writeup: `Deck's ginger sidekick and Joe Harrington impersonator, Jager champ and poker shithouse. Evans had a quarter final run in 19/20 but has been resigned to the plate early stages since - He'd rather be shoving Pocket Aces anyway.`,
    highestAverage: { value: 47.5, link: "https://recap.dartconnect.com/matches/67827751167d4efa93f7c0d5" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: ["1st non Hallam Student to play in the event"],
    placeholder: false,
    timeline: [
      { year: "19/20", competition: "Handley Cup", result: "Quarter-Final", opponentId: "dom-tofts", opponentName: "Dom Tofts", score: "1-3", scoreReconstructed: true, average: null, link: null },
      { year: "22/23", competition: "Parson's Plate", result: "Quarter-Final", opponentId: "calum-brown", opponentName: "Calum Brown", score: "0-3", scoreReconstructed: false, average: null, link: null },
      { year: "24/25", competition: "Parson's Plate", result: "Last 32", opponentId: "oliver-wilson", opponentName: "Oliver Wilson", score: "1-3", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "lewis-ruston",
    name: "Lewis Ruston",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Last 16" },
    nickname: "Stumpy",
    writeup: `Spent more times playing with the speakers than hitting trebles`,
    highestAverage: { value: 46.05, link: "https://recap.dartconnect.com/matches/67827fc7167d4efa93f7c7d2" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "24/25", competition: "Parson's Plate", result: "Last 16", opponentId: "oliver-wilson", opponentName: "Oliver Wilson", score: "0-3", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "alex-mccowen",
    name: "Alex McCowen",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Quarter-Final" },
    nickname: "Pay 2 Win",
    writeup: `Pay 2 Win, should be spending some more cash on the board and at the bar. A debut last year coming to an end at the hands of one Wicked Wilson`,
    highestAverage: { value: 39.12, link: "https://recap.dartconnect.com/matches/6782d243167d4efa93f821af" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "24/25", competition: "Parson's Plate", result: "Quarter-Final", opponentId: "oliver-wilson", opponentName: "Oliver Wilson", score: "0-3", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "oli-bartlett",
    name: "Oli Bartlett",
    appearances: 5,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Quarter-Final" },
    nickname: "Bomber",
    writeup: `The Bomber! After teaching Joe Evans how to smash Jager bombs to hitting 180s and now is shaping the minds of tomorrow - the ex President is a welcome sight at the Handley cup, making 5 appearances and always making it through the groups, a last minute dodgy Lasagne forced Oli out of last year's comp, we're hoping to see the bomber make a comeback in 2027!`,
    highestAverage: { value: 49.09, link: "https://recap.dartconnect.com/matches/6782aeae167d4efa93f7f453" },
    oneEighties: 2,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "18/19", competition: "Handley Cup", result: "Quarter-Final", opponentId: "will-sturla", opponentName: "Will Sturla", score: "2-4", scoreReconstructed: false, average: null, link: null },
      { year: "19/20", competition: "Handley Cup", result: "Last 16", opponentId: "todd-haynes", opponentName: "Todd Haynes", score: "2-3", scoreReconstructed: true, average: null, link: null },
      { year: "20/21", competition: "Handley Cup", result: "Quarter-Final", opponentId: "dale-dennett", opponentName: "Dale Dennett", score: "1-4", scoreReconstructed: true, average: null, link: null },
      { year: "22/23", competition: "Handley Cup", result: "Quarter-Final", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "0-5", scoreReconstructed: false, average: null, link: null },
      { year: "24/25", competition: "Handley Cup", result: "Last 16", opponentId: "oliver-burgess", opponentName: "Oliver Burgess", score: "0-4", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "sam-taylor",
    name: "Sam Taylor",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Walkover" },
    nickname: "Tism",
    writeup: `1 appearance 1 walkout due to a hissy fit. A bad beat in Darts and Poker, now that's rare!`,
    highestAverage: { value: 49.46, link: "https://recap.dartconnect.com/matches/67827ade167d4efa93f7c3de" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "24/25", competition: "Handley Cup", result: "Walkover", opponentId: null, opponentName: null, score: null, scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "fillip-brom",
    name: "Fillip Brom",
    appearances: 2,
    nationality: "Slovakia",
    bestRun: { label: "Handley Cup", detail: "Last 16" },
    nickname: "The Conqueror",
    writeup: `The Martin Dubravka of Hallam darts, a safe pair of hands and part of the golden age of Hallam, arguably underperformed when at the Handley cup with other priorities on the day getting the better of him`,
    highestAverage: { value: 59.58, link: "https://recap.dartconnect.com/matches/6782c746167d4efa93f8127b" },
    oneEighties: 2,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "23/24", competition: "Handley Cup", result: "Last 16", opponentId: "morgan-shillito", opponentName: "Morgan Shillito", score: "1-4", scoreReconstructed: true, average: null, link: null },
      { year: "24/25", competition: "Handley Cup", result: "Last 16", opponentId: "james-buckby", opponentName: "James Buckby", score: "1-4", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "zach-hodgson",
    name: "Zach Hodgson",
    appearances: 3,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Quarter-Final" },
    nickname: "The Swan",
    writeup: `Wycombe. MMA. Darts. In that order. The Swan just oozes aura. Only failing to get through the groups once in his time in the Handley Cup, despite some brutal draws in the groups and KOs. Wilson was missing his double act last year, he hopes to see Zach attend or at least tell us that he can't make it for 2027`,
    highestAverage: { value: 50.38, link: "https://recap.dartconnect.com/matches/6782d340167d4efa93f822ee" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "22/23", competition: "Handley Cup", result: "Quarter-Final", opponentId: "oliver-burgess", opponentName: "Oliver Burgess", score: "0-4", scoreReconstructed: false, average: null, link: null },
      { year: "23/24", competition: "Handley Cup", result: "Last 16", opponentId: "dale-dennett", opponentName: "Dale Dennett", score: "2-4", scoreReconstructed: true, average: null, link: null },
      { year: "24/25", competition: "Parson's Plate", result: "Quarter-Final", opponentId: "dan-harrison", opponentName: "Dan Harrison", score: "1-3", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "tom-khan",
    name: "Tom Khan",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Last 16" },
    nickname: "Trebleless",
    writeup: `The lowest average in his only appearance, a legacy but at what cost`,
    highestAverage: { value: 44.26, link: "https://recap.dartconnect.com/matches/67827fe3167d4efa93f7c7e8" },
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "24/25", competition: "Parson's Plate", result: "Last 16", opponentId: "alex-mccowen", opponentName: "Alex McCowen", score: "1-3", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "will-sturla",
    name: "Will Sturla",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Winner" },
    nickname: "The Conqueror",
    writeup: `What a man, turns up, wins, leaves for France and never comes back. The legacy of his name is whispered to Marshall like a ghost, rumours are swirling that The Tall Ginger Darting Machine will be making an appearance sooner rather than later`,
    highestAverage: null,
    oneEighties: 1,
    quickestLeg: null,
    highestCheckout: { value: 104, link: null },
    facts: [],
    placeholder: false,
    timeline: [
      { year: "18/19", competition: "Handley Cup", result: "Winner", opponentId: "dale-dennett", opponentName: "Dale Dennett", score: "6-1", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "kieran-fitzgibbon",
    name: "Kieran Fitzgibbon",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Semi-Final" },
    nickname: "Shabba",
    writeup: `Shabba! One of the Porkys Pigs and fitting that he made an appearance in the Handley Cup and semi final too! Shabba was always in the As and spoiling the party in the Handley Cup before losing 5-3 to Dale in the first semi final ever played`,
    highestAverage: null,
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "18/19", competition: "Handley Cup", result: "Semi-Final", opponentId: "dale-dennett", opponentName: "Dale Dennett", score: "3-5", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "nathan-hemmingway",
    name: "Nathan Hemmingway",
    appearances: 5,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Semi-Final" },
    nickname: "Ginger Spice",
    writeup: `Ginger Spice normally fails to complete his darting obligations after a group stage filled with more shots and doubles than darts thrown, Nath has been to 5 Handley cups and has nearly got his hands on the Plate a number of times but hasn't been spotted at the Handley cup in a few years, many hoping for a comeback for the shithouse!`,
    highestAverage: null,
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "18/19", competition: "Handley Cup", result: "Last 16", opponentId: "kieran-fitzgibbon", opponentName: "Kieran Fitzgibbon", score: "0-3", scoreReconstructed: false, average: null, link: null },
      { year: "19/20", competition: "Parson's Plate", result: "Runner-Up", opponentId: "laura-bugge", opponentName: "Laura Bugge", score: "1-2", scoreReconstructed: true, average: null, link: null },
      { year: "20/21", competition: "Parson's Plate", result: "Semi-Final", opponentId: "oli-gubbins", opponentName: "Oli Gubbins", score: "2-4", scoreReconstructed: true, average: null, link: null },
      { year: "21/22", competition: "Handley Cup", result: "Quarter-Final", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "0-3", scoreReconstructed: false, average: null, link: null },
      { year: "22/23", competition: "Handley Cup", result: "Quarter-Final", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "0-4", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "luke-hider",
    name: "Luke Hider",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Last 16" },
    nickname: "Hitlan",
    writeup: `A good answer to the pub quiz question of players who attended the first event, Hider and Fingram were members of the Ben Laurence mafia and attended the cup in his absence`,
    highestAverage: null,
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "18/19", competition: "Handley Cup", result: "Last 16", opponentId: "todd-haynes", opponentName: "Todd Haynes", score: "1-3", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "luke-gribbin",
    name: "Luke Gribbin",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Last 16" },
    nickname: "The Bouncer",
    writeup: `Spent his time off the board telling people to calm down in Corp and Code. The Boucher all but dispersed after his fresher year and debut`,
    highestAverage: null,
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "18/19", competition: "Handley Cup", result: "Last 16", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "0-3", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "joe-harrington",
    name: "Joe Harrington",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Last 16" },
    nickname: "The Who",
    writeup: `The actual Joe Harrington. The beard to be feared and a natural talent but spent more time sipping real ale than pinning doubles`,
    highestAverage: null,
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "18/19", competition: "Handley Cup", result: "Last 16", opponentId: "deck-ingber", opponentName: "Deck Ingber", score: "1-3", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "daniel-fingram",
    name: "Daniel Fingram",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Last 16" },
    nickname: "The Man",
    writeup: `The other half of the Laurence mafia. Dan the man had to face Sturla in the opener in his only game in Handley cup history, ouch!`,
    highestAverage: null,
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "18/19", competition: "Handley Cup", result: "Last 16", opponentId: "will-sturla", opponentName: "Will Sturla", score: "0-3", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "callum-read",
    name: "Callum Read",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Last 16" },
    nickname: "Stealth",
    writeup: `Stealth....few knew of him, even fewer ever heard him. Made Darren Webster look like the Great Khali. But this throw was a thing of beauty. Not seen Callum since the first edition of the Handley cup, but his legacy lives on`,
    highestAverage: null,
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "18/19", competition: "Handley Cup", result: "Last 16", opponentId: "dan-harrison", opponentName: "Dan Harrison", score: "2-3", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "oli-gubbins",
    name: "Oli Gubbins",
    appearances: 3,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Runner-Up" },
    nickname: "Gubby",
    writeup: `It's been a while since we've seen Gubby at the Handley Cup - a key member of the society during his student days in both the As and the Bs, boasts a quarter final in the first event and then Parsons Plate defeats to both winners - 2 finals but powerless to beat Cam or Calum Brown, hope to see you again soon Gubbins!`,
    highestAverage: null,
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: { value: 104, link: null },
    facts: [],
    placeholder: false,
    timeline: [
      { year: "19/20", competition: "Handley Cup", result: "Quarter-Final", opponentId: "curtis-thorpe", opponentName: "Curtis Thorpe", score: "2-3", scoreReconstructed: true, average: null, link: null },
      { year: "20/21", competition: "Parson's Plate", result: "Runner-Up", opponentId: "cam-thorpe", opponentName: "Cam Thorpe", score: "1-5", scoreReconstructed: true, average: null, link: null },
      { year: "22/23", competition: "Parson's Plate", result: "Runner-Up", opponentId: "calum-brown", opponentName: "Calum Brown", score: "2-5", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "neiran-donnelley",
    name: "Neiran Donnelley",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Quarter-Final" },
    nickname: "No Show",
    writeup: `Honestly, who?`,
    highestAverage: null,
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "22/23", competition: "Parson's Plate", result: "Quarter-Final", opponentId: "harvey-thompson", opponentName: "Harvey Thompson", score: "0-3", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "nathan-stewart",
    name: "Nathan Stewart",
    appearances: 2,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Semi-Final" },
    nickname: "Little",
    writeup: `The other half of the Thompson and Stewart duo, Nath was someone in the dark days of Hallam that was always playing for the each and drafting, a good run in the Parson's plate on debut being the highlight for the Alumni man!`,
    highestAverage: null,
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "22/23", competition: "Parson's Plate", result: "Quarter-Final", opponentId: "oli-gubbins", opponentName: "Oli Gubbins", score: "0-4", scoreReconstructed: false, average: null, link: null },
      { year: "23/24", competition: "Parson's Plate", result: "Semi-Final", opponentId: "todd-haynes", opponentName: "Todd Haynes", score: "1-4", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "laura-bugge",
    name: "Laura Bugge",
    appearances: 2,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Winner" },
    nickname: "Budgie",
    writeup: `The only women in Handley Cup history to pick up a title, it was just a packet of Jammy dodger during the bomber reign. Laura also attended the COVID-19 edition losing to Cam in the quarters of the plate`,
    highestAverage: null,
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "19/20", competition: "Parson's Plate", result: "Winner", opponentId: "nathan-hemmingway", opponentName: "Nathan Hemmingway", score: "2-1", scoreReconstructed: true, average: null, link: null },
      { year: "20/21", competition: "Parson's Plate", result: "Quarter-Final", opponentId: "cam-thorpe", opponentName: "Cam Thorpe", score: "0-3", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "jamesey-ennis",
    name: "Jamesey Ennis",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Semi-Final" },
    nickname: "The Phantom",
    writeup: `The phantom for a season, only entering the year Hallam had lockdown as he wouldn't be seen dead in Sheffield after costing Hallam the Pool and Darts varsity twice in 1 season, pretty impressive!`,
    highestAverage: null,
    oneEighties: 2,
    quickestLeg: null,
    highestCheckout: { value: 111, link: null },
    facts: ["Only ever play the Handley Cup Online and not in Person"],
    placeholder: false,
    timeline: [
      { year: "20/21", competition: "Parson's Plate", result: "Semi-Final", opponentId: "cam-thorpe", opponentName: "Cam Thorpe", score: "2-4", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "jack-briggs",
    name: "Jack Briggs",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Quarter-Final" },
    nickname: "Brick",
    writeup: `Jack attended in Chesterfield and should've thrown a brick at the board to be more effective`,
    highestAverage: null,
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "23/24", competition: "Parson's Plate", result: "Quarter-Final", opponentId: "finley-sanderson", opponentName: "Finley Sanderson", score: "2-3", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "huxley-largan",
    name: "Huxley Largan",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Quarter-Final" },
    nickname: "Early Finish",
    writeup: `Who? Dispersed before the groups ended and faded into the ether`,
    highestAverage: null,
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "22/23", competition: "Parson's Plate", result: "Quarter-Final", opponentId: "todd-haynes", opponentName: "Todd Haynes", score: "0-4", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "henry-wheeler",
    name: "Henry Wheeler",
    appearances: 1,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Quarter-Final" },
    nickname: "Hotwheels",
    writeup: `Hotwheels is a man in infamy but to the older lads at Hallam the drink tales are legendary, the darts...not so much (Curtis definitely pushed him down the stairs in Corp)`,
    highestAverage: null,
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "19/20", competition: "Parson's Plate", result: "Quarter-Final", opponentId: "alex-wright", opponentName: "Alex Wright", score: "1-2", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "harvey-thompson",
    name: "Harvey Thompson",
    appearances: 2,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Semi-Final" },
    nickname: "The Roar",
    writeup: `Best known for showing Luke Davies how to play games of darts, the roar made 2 appearances in the Handley Cup sinking more pints than legs won, but still well known for being a mainstay in helping Hallam get back on its feet after the near collapse of the society`,
    highestAverage: null,
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "22/23", competition: "Parson's Plate", result: "Semi-Final", opponentId: "calum-brown", opponentName: "Calum Brown", score: "0-4", scoreReconstructed: false, average: null, link: null },
      { year: "23/24", competition: "Parson's Plate", result: "Quarter-Final", opponentId: "todd-haynes", opponentName: "Todd Haynes", score: "0-3", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "connor-bowler",
    name: "Connor Bowler",
    appearances: 2,
    nationality: "England",
    bestRun: { label: "Handley Cup", detail: "Runner-Up" },
    nickname: "Tenpin",
    writeup: `What can you say about Tenpin, the bloke's talent is madness. Running Marshall close 6-4 in his first year before losing a nailbiter to OPB, we've not seen Bowler in a few years as he's too busy smashing it up in the WDF. A front runner when he attends, we're hoping to see Tenpin back mixing it with the very best the Handley Cup has to offer!`,
    highestAverage: null,
    oneEighties: 8,
    quickestLeg: { darts: 15, link: null },
    highestCheckout: { value: 138, link: null },
    facts: [],
    placeholder: false,
    timeline: [
      { year: "22/23", competition: "Handley Cup", result: "Runner-Up", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "4-6", scoreReconstructed: true, average: null, link: null },
      { year: "23/24", competition: "Handley Cup", result: "Semi-Final", opponentId: "oliver-burgess", opponentName: "Oliver Burgess", score: "3-5", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "cam-thorpe",
    name: "Cam Thorpe",
    appearances: 2,
    nationality: "England",
    bestRun: { label: "Parson's Plate", detail: "Winner" },
    nickname: "C-Dog",
    writeup: `The only Thorpe who can win anything - taught everything he knew by Mr Ingber the master of the ginger fringe and the leg kick boasts not 1 but 2 parsons plate titles to his name. C-Dog just wins finals, shame he couldn't get out of his group!`,
    highestAverage: null,
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "20/21", competition: "Parson's Plate", result: "Winner", opponentId: "oli-gubbins", opponentName: "Oli Gubbins", score: "5-1", scoreReconstructed: true, average: null, link: null },
      { year: "21/22", competition: "Parson's Plate", result: "Winner", opponentId: "alex-wright", opponentName: "Alex Wright", score: "3-0", scoreReconstructed: false, average: null, link: null },
    ]
  },
  {
    id: "calum-brown",
    name: "Calum Brown",
    appearances: 1,
    nationality: "Scotland",
    bestRun: { label: "Parson's Plate", detail: "Winner" },
    nickname: "The Tache",
    writeup: `He came he saw he conquered! Brownie was a mainstay in the 2019/2020 season in the A team before Covid before making a short lived appearance back in 2023 showing he had not missed a step. Cycling his way to the Parsons plate beating his pal Gubbins in the final, before riding off into the sunset`,
    highestAverage: null,
    oneEighties: null,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "22/23", competition: "Parson's Plate", result: "Winner", opponentId: "oli-gubbins", opponentName: "Oli Gubbins", score: "5-2", scoreReconstructed: true, average: null, link: null },
    ]
  },
  {
    id: "bart-timmer",
    name: "Bart Timmer",
    appearances: 1,
    nationality: "Netherlands",
    bestRun: { label: "Handley Cup", detail: "Runner-Up" },
    nickname: "The Dart",
    writeup: `Never fall in love with a loan player - Mr Timmer himself a finalist with an impressive game against Marshall! Timmer promises a comeback when his poker allows. The greatest overseas player in the Hallam darts history? Probably!`,
    highestAverage: null,
    oneEighties: 1,
    quickestLeg: null,
    highestCheckout: null,
    facts: [],
    placeholder: false,
    timeline: [
      { year: "21/22", competition: "Handley Cup", result: "Runner-Up", opponentId: "charlie-marshall", opponentName: "Charlie Marshall", score: "3-5", scoreReconstructed: true, average: null, link: null },
    ]
  },
];