/* =============================================================================
   THE HANDLEY CUP — RECORDS & TRIVIA
   Generated from your facts/comments data, filtered to genuine records and
   trivia (achievement counts like "7x Champion" are left out since Power
   Rankings and Roll of Honour already cover those).

   Gated behind FACTS_READY (declared in players-data.js) — this page shows
   a placeholder until you flip that to true.
   ========================================================================= */

const RECORDS = [
  { category: "Career Records", text: "Most appearances without getting on the Sheet (7)", playerName: "Alex Wright", playerId: "alex-wright" },
  { category: "Firsts & Onlys", text: "Most-capped female player (4) — also the first player from a university outside Hallam to play (Salford)", playerName: "Jessie Sale", playerId: "jessie-sale" },
  { category: "Firsts & Onlys", text: "Only Italian player to appear in the Handley Cup", playerName: "Eddie Castaldo", playerId: "eddie-castaldo" },
  { category: "Career Records", text: "Longest wait between Unique Performance awards (5 years)", playerName: "Eddie Castaldo", playerId: "eddie-castaldo" },
  { category: "Career Records", text: "Most group wins (7) and most titles (7)", playerName: "Charlie Marshall", playerId: "charlie-marshall" },
  { category: "Firsts & Onlys", text: "Only player never to drop a leg in a group stage (2020/21)", playerName: "Charlie Marshall", playerId: "charlie-marshall" },
  { category: "Career Records", text: "Most 180s (35), highest checkout (148) and quickest leg (12 darts)", playerName: "Charlie Marshall", playerId: "charlie-marshall" },
  { category: "Career Records", text: "100% group stage advancement — Dale Dennett has never once missed out on the knockouts from his group", playerName: "Dale Dennett", playerId: "dale-dennett" },
  { category: "Career Records", text: "Dale Dennett and Oliver Burgess are tied for the most Cup Final defeats (2 each) — Dennett's came by a brutal combined 12-1 (1 leg won across both), Burgess's by a much closer combined 11-6", playerName: "Dale Dennett", playerId: "dale-dennett" },
  { category: "Career Records", text: "Since his only career loss — the 18/19 semi-final — Charlie Marshall has not lost a single match since: 59 wins in a row across every group and knockout game played, and counting", playerName: "Charlie Marshall", playerId: "charlie-marshall" },
  { category: "Career Records", text: "Charlie Marshall has won 224 legs in his Handley Cup career — nearly double the next-best total, Dale Dennett's 131", playerName: "Charlie Marshall", playerId: "charlie-marshall" },
  { category: "Other Notable Facts", text: "The shortest Final on record is Laura Bugge's 2-1 win over Nathan Hemmingway in the 19/20 Parson's Plate — just 3 legs. The longest is the 25/26 Handley Cup Final, Charlie Marshall's 7-4 win over Oliver Burgess — 11 legs", playerName: "", playerId: "" },
  { category: "Other Notable Facts", text: "Oli Gubbins is the only player to lose two different Parson's Plate finals (20/21, 22/23) — managing just 3 legs across both, a mirror of Dale Dennett's misfortune in the Cup", playerName: "Oli Gubbins", playerId: "oli-gubbins" },
  { category: "Firsts & Onlys", text: "Three players have won the Parson's Plate in their tournament debut: Laura Bugge (19/20), Cam Thorpe (20/21) and Calum Brown (22/23)", playerName: "", playerId: "" },
  { category: "Firsts & Onlys", text: "First University of Derby player to play in the Handley Cup", playerName: "Will North", playerId: "will-north" },
  { category: "Other Notable Facts", text: "Parson's Plate champion in 2024/25", playerName: "Hugo Nilsson", playerId: "hugo-nilsson" },
  { category: "Firsts & Onlys", text: "Only Swedish player to play in the Handley Cup", playerName: "Hugo Nilsson", playerId: "hugo-nilsson" },
  { category: "Firsts & Onlys", text: "Only Jamaican player to ever play in the Handley Cup", playerName: "Dereece O'Hara", playerId: "dereece-ohara" },
  { category: "Firsts & Onlys", text: "Only player to miss match darts against Charlie Marshall in a year he lifted the title (2023/24)", playerName: "Jamie Flint", playerId: "jamie-flint" },
  { category: "Career Records", text: "Longest wait between appearances (4 events)", playerName: "Dan Rushton", playerId: "dan-rushton" },
  { category: "Firsts & Onlys", text: "First University of Sheffield player to appear at the Handley Cup", playerName: "Alex Botha", playerId: "alex-botha" },
  { category: "Firsts & Onlys", text: "Only South African player to play at the Handley Cup", playerName: "Alex Botha", playerId: "alex-botha" },
  { category: "Firsts & Onlys", text: "First non-Hallam student to play in the event", playerName: "Joe Evans", playerId: "joe-evans" },
  { category: "Firsts & Onlys", text: "Only Slovakian player to play in the Handley Cup", playerName: "Fillip Brom", playerId: "fillip-brom" },
  { category: "Firsts & Onlys", text: "Only unbeaten player in Handley Cup history", playerName: "Will Sturla", playerId: "will-sturla" },
  { category: "Firsts & Onlys", text: "Only female to achieve a Unique Performance award", playerName: "Laura Bugge", playerId: "laura-bugge" },
  { category: "Firsts & Onlys", text: "Has only ever played the Handley Cup online, never in person", playerName: "Jamesey Ennis", playerId: "jamesey-ennis" },
  { category: "Firsts & Onlys", text: "Only two-time Parson's Plate champion", playerName: "Cam Thorpe", playerId: "cam-thorpe" },
  { category: "Firsts & Onlys", text: "Only non-UK player to make a Final", playerName: "Bart Timmer", playerId: "bart-timmer" },
  { category: "Firsts & Onlys", text: "Only Dutch player to appear in the Handley Cup", playerName: "Bart Timmer", playerId: "bart-timmer" },
  { category: "Career Records", text: "191 entries in Handley Cup history — the most-attended event was 2025/26 (47), the least-attended was 2021/22 (10)", playerName: "", playerId: "" },
  { category: "Career Records", text: "77 unique players have entered the Handley Cup", playerName: "", playerId: "" },
  { category: "Career Records", text: "143 180s hit in Handley Cup history — Charlie Marshall leads with 35, Morgan Shillito 2nd with 20, Oliver Burgess 3rd with 12", playerName: "Charlie Marshall", playerId: "charlie-marshall" },
  { category: "Career Records", text: "26 unique players have hit a ton-plus checkout", playerName: "", playerId: "" },
  { category: "Career Records", text: "31 unique players have hit a 180", playerName: "", playerId: "" },
  { category: "Firsts & Onlys", text: "8 nationalities have played in the Handley Cup: English, Scottish, Italian, Jamaican, Swedish, Slovakian, South African and Dutch", playerName: "", playerId: "" },
  { category: "Firsts & Onlys", text: "5 unique locations have hosted the Handley Cup: HUBS, Peaks, Lennon's Sports Bar, Yorkshire Main, and online during COVID-19", playerName: "", playerId: "" },
  { category: "Career Records", text: "30 players have progressed to at least the semi-final stage (Cup or Plate)", playerName: "", playerId: "" },
  { category: "Career Records", text: "40 players have never made it \"on the sheet\" (never recorded a 180, a checkout or a quick leg)", playerName: "", playerId: "" },
  { category: "Career Records", text: "The most debutants in a single event was 2025/26, with 17", playerName: "", playerId: "" },
  { category: "Career Records", text: "Only 4 players have attended every single Handley Cup: Curtis Thorpe, Charlie Marshall, Jamie Flint and Todd Haynes", playerName: "", playerId: "" },
  { category: "Firsts & Onlys", text: "6 different players have won the Parson's Plate — Cam Thorpe is the only one to win it more than once (2)", playerName: "Cam Thorpe", playerId: "cam-thorpe" },
  { category: "Firsts & Onlys", text: "Only player to attend every event without ever reaching the Cup or Plate final", playerName: "Curtis Thorpe", playerId: "curtis-thorpe" },
  { category: "Firsts & Onlys", text: "Only female Parson's Plate champion", playerName: "Laura Bugge", playerId: "laura-bugge" },
  { category: "Firsts & Onlys", text: "Joe Evans, Blake Longden, Josh Longden and Bradley Truelove are the only players to play the Handley Cup without ever attending university", playerName: "", playerId: "" },
  { category: "Firsts & Onlys", text: "Jessie Sale, Alex Botha, Will North and Sam Taylor are the only players to attend a university other than Hallam while playing in the Handley Cup", playerName: "", playerId: "" },
  { category: "Firsts & Onlys", text: "The Cup Final has gone to a last-leg decider only once, in 2019/20, between Jamie Flint and Charlie Marshall", playerName: "", playerId: "" },
  { category: "Firsts & Onlys", text: "8 Handley Cup players have won a game on the PDC Development Tour — Morgan Shillito, James Buckby, Oliver Burgess, Jamie Flint, Curtis Thorpe, Eddie Castaldo, Louis Bell and Connor Bowler — though none of them have won the Handley Cup itself", playerName: "", playerId: "" },
  { category: "Firsts & Onlys", text: "100% of Scottish players to enter the Handley Cup have walked away with a trophy", playerName: "Calum Brown", playerId: "calum-brown" },
  { category: "Firsts & Onlys", text: "The only seeded player never to appear in the Handley Cup: Ben Laurence", playerName: "Ben Laurence", playerId: "" },
  { category: "Firsts & Onlys", text: "The 2024/25 Handley Cup was the first ever run on DartConnect", playerName: "", playerId: "" },
  { category: "Firsts & Onlys", text: "Only player to ever attend the Handley Cup on their birthday", playerName: "Dom Tofts", playerId: "dom-tofts" },
  { category: "Career Records", text: "Charlie Marshall vs Jamie Flint is both the most-played (6 times) and most one-sided (6-0) rivalry in Handley Cup history — 31 legs played between them in total", playerName: "", playerId: "" },
  { category: "Career Records", text: "Excluding Marshall vs Flint, the most-played fixture in Handley Cup history is a five-way tie at 4 meetings each: Marshall vs Haynes, Flint vs Haynes, Dennett vs Flint, Marshall vs Burgess, and Thorpe vs Castaldo", playerName: "", playerId: "" },
  { category: "Career Records", text: "599 matches have been played across Handley Cup history — 426 in the group stage, 173 in the knockouts (Cup and Plate combined)", playerName: "", playerId: "" },
  { category: "Career Records", text: "2,396 legs have been played across every recorded Handley Cup and Parson's Plate match — 1,535 in the group stage, 861 in the knockouts", playerName: "", playerId: "" },
  { category: "Career Records", text: "Oliver Burgess and Dale Dennett are tied for the most semi-final-or-better appearances without ever winning a title (4 each) — Burgess did it in just 4 total appearances", playerName: "", playerId: "" },
  { category: "Other Notable Facts", text: "The longest knockout match outside a Final on record is Charlie Marshall's 5-4 semi-final win over Jamie Flint in 2023/24 — 9 legs", playerName: "", playerId: "" },
  { category: "Career Records", text: "Almost half of everyone who's ever entered — 36 of 77 players (46.8%) — has only ever played once", playerName: "", playerId: "" },
  { category: "Career Records", text: "The most-played group stage rivalry is a six-way tie at 3 meetings each: Alex Wright vs Charlie Marshall, Curtis Thorpe vs Todd Haynes, Jamie Flint vs Todd Haynes, Alex Wright vs Jamie Flint, Charlie Marshall vs Jessie Sale, and Charlie Marshall vs Jamie Flint", playerName: "", playerId: "" },
  { category: "Career Records", text: "Alex Wright and Curtis Thorpe have the biggest combined appearance count (15, from 7 and 8 respectively) of any pair who have never once faced each other", playerName: "", playerId: "" },
  { category: "Career Records", text: "Charlie Marshall has never lost a single group-stage match in Handley Cup history — 34 wins from 34 games", playerName: "Charlie Marshall", playerId: "charlie-marshall" },
  { category: "Other Notable Facts", text: "The tightest group stage on record is 2025/26 Group B, where every player finished within 2 wins of each other", playerName: "", playerId: "" },
  { category: "Other Notable Facts", text: "The most lopsided group stage on record is 2023/24 Group A, with a 6-win spread between the top and bottom of the table", playerName: "", playerId: "" },
  { category: "Career Records", text: "Oliver Burgess has played in 4 Handley Cups and reached at least the semi-finals in every single one", playerName: "Oliver Burgess", playerId: "oliver-burgess" },
  { category: "Other Notable Facts", text: "Charlie Marshall didn't drop a single leg until the Final in 2021/22", playerName: "Charlie Marshall", playerId: "charlie-marshall" },
  { category: "Firsts & Onlys", text: "All 8 of Curtis Thorpe's knockout losses have come against a different opponent each time", playerName: "Curtis Thorpe", playerId: "curtis-thorpe" },
  { category: "Other Notable Facts", text: "The only Handley Cup missing spreadsheet records is the one year Dale Dennett didn't attend", playerName: "Dale Dennett", playerId: "dale-dennett" },
  { category: "Other Notable Facts", text: "Dale Dennett and Morgan Shillito are the only players to be whitewashed in a Final", playerName: "", playerId: "" },
  { category: "Other Notable Facts", text: "Todd Haynes' 2023/24 Plate win ended the longest trophy drought in Handley Cup history — 6 years", playerName: "Todd Haynes", playerId: "todd-haynes" },
  { category: "Other Notable Facts", text: "Kelham Elliot and Caitlin Cope played the only game in Handley Cup history to last over an hour", playerName: "", playerId: "" },
  { category: "Career Records", text: "1,535 legs have been played across every group-stage match in Handley Cup history (426 matches)", playerName: "", playerId: "" },
  { category: "Other Notable Facts", text: "More than half of all group-stage matches (218 of 426, 51.2%) have ended in a clean 3-0 whitewash", playerName: "", playerId: "" },
  { category: "Career Records", text: "Bradley Truelove has the best group-stage win rate of anyone not named Marshall — 93.3% (14 of 15)", playerName: "Bradley Truelove", playerId: "bradley-truelove" },
  { category: "Career Records", text: "The most common knockout scoreline in Handley Cup history is 3-0, coming up 27 times — closely followed by 4-1 (26 times)", playerName: "", playerId: "" },
  { category: "Not Charlie Marshall", text: "Will Sturla is the only other player to have ever won the Handley Cup outright — the inaugural 18/19 champion, beating a young Dale Dennett 6-1 in the final", playerName: "Will Sturla", playerId: "will-sturla" },
  { category: "Not Charlie Marshall", text: "Dale Dennett has the most group-stage wins of anyone, discounting every match involving Marshall — 26 wins from 28 played (92.9%)", playerName: "Dale Dennett", playerId: "dale-dennett" },
  { category: "Not Charlie Marshall", text: "Dale Dennett also leads all knockout-round wins outside of matches involving Marshall, with 11", playerName: "Dale Dennett", playerId: "dale-dennett" },
  { category: "Not Charlie Marshall", text: "Morgan Shillito has the most 180s of anyone else (20)", playerName: "Morgan Shillito", playerId: "morgan-shillito" },
  { category: "Not Charlie Marshall", text: "James Buckby holds the highest single-game average of anyone else (88.26)", playerName: "James Buckby", playerId: "james-buckby" },
  { category: "Not Charlie Marshall", text: "Dale Dennett holds the highest checkout of anyone else (146)", playerName: "Dale Dennett", playerId: "dale-dennett" },
  { category: "Not Charlie Marshall", text: "The quickest leg by anyone else is a four-way tie at 13 darts: Bradley Truelove, Dan Rushton, James Buckby and Oliver Burgess", playerName: "", playerId: "" },
  { category: "Not Charlie Marshall", text: "Todd Haynes, Jamie Flint and Curtis Thorpe are tied for the most appearances by anyone else (8 each)", playerName: "", playerId: "" },
  { category: "Career Records", text: "Todd Haynes has faced more unique opponents than anyone else in Handley Cup history — 34, just ahead of Charlie Marshall's 33", playerName: "Todd Haynes", playerId: "todd-haynes" },
  { category: "Other Notable Facts", text: "The tournament has grown enormously — the inaugural 18/19 event saw 15 matches and 72 legs played; the 25/26 event alone saw 160 matches and 661 legs, more than the first four seasons combined", playerName: "", playerId: "" },
  { category: "Other Notable Facts", text: "18.5% of knockout matches in Handley Cup history (32 of 173) have been decided by a single leg — the tightest possible margin", playerName: "", playerId: "" },
  { category: "Firsts & Onlys", text: "The Parson's Plate has crowned an overseas champion, beating English opposition, in three of the last four seasons: Calum Brown (Scotland, 22/23), Hugo Nilsson (Sweden, 24/25) and Eddie Castaldo (Italy, 25/26)", playerName: "", playerId: "" },
  { category: "Firsts & Onlys", text: "Sam Taylor is the only player in Handley Cup history to enter and never once reach the knockouts — eliminated in the group stage in his sole appearance", playerName: "Sam Taylor", playerId: "sam-taylor" },
  { category: "Career Records", text: "Charlie Marshall's career leg differential is +176 across 62 matches — more than three times the next best, Dale Dennett's +56", playerName: "Charlie Marshall", playerId: "charlie-marshall" },
  { category: "Other Notable Facts", text: "Alex Wright has the worst leg differential of any regular (minimum 15 matches played) at -58 across 41 matches — a beloved fixture of the event for 7 years running, but the results haven't followed", playerName: "Alex Wright", playerId: "alex-wright" },
  { category: "Career Records", text: "Dale Dennett vs Jamie Flint is the only rivalry with 4 or more meetings to finish perfectly balanced — 2 wins apiece", playerName: "", playerId: "" },
  { category: "Other Notable Facts", text: "Only 20 of the 77 players who've ever entered the Handley Cup (26%) have reached a Cup or Plate Final — the other 74% have gone home empty-handed every time", playerName: "", playerId: "" },
];
